x-def-logging: &default-logging
  logging:
    driver: "loki"
    options:
      # Адрес Loki, куда складывать логи
      # обратите внимание, что здесь используется не имя сервиса loki, а локальный хост, на который проброшен порт Loki.
      # Это сделано потому, что логи будет писать docker engine, который расположен на хостовой машине.
      # И он не знает имени хоста контейнера Loki, которое ему присвоил compose во внутренней сети проекта.
      loki-url: "http://localhost:3100/loki/api/v1/push"
      loki-batch-size: "100"
      loki-retries: 2
      loki-max-backoff: 1000ms
      loki-timeout: 1s

services:
  loki:
    hostname: loki
    image: grafana/loki:latest
    environment:
      - TZ=${SYSTEM_TIMEZONE:-Europe/Moscow}
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    hostname: grafana
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      # Включим доступ без авторизации
      - GF_AUTH_ANONYMOUS_ENABLED=true # Не используйте **ANONYMOUS** настройки в проде.
      # Дадим права администратора при анонимном входе
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - TZ=${SYSTEM_TIMEZONE:-Europe/Moscow}
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"

  library_rest_service:
    build:
      context: ../..
      dockerfile: deployment/development/Dockerfile
    environment:
      - TZ=${SYSTEM_TIMEZONE:-Europe/Moscow}
    env_file:
      - .env
    <<: *default-logging
    ports:
      - "8000:8000"
    depends_on:
      library_db:
        condition: service_healthy

  library_db:
    image: postgres:latest
    container_name: library-database
    env_file:
      - .env
    volumes:
      - ./.database/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    profiles: [ "tools" ]
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${SSL_MODE}"
      ]
    command: ["up", "down"]
    depends_on:
      library_db:
        condition: service_healthy

